/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmaRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.prescribeMedicine;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehadevarapalli
 */
public class PharmaWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmaWorkAreaJPanel
     */
     private JPanel userProcessContainer;
     private UserAccount account;
     private Organization organization;
     private Enterprise enterprise;
     private EcoSystem business;
//     private UserAccount person;
    public PharmaWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.account = account;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        lblVal.setText(account.getEmployee().getName());
//        this.person = person;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnavailable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicallist = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnNotavailable = new javax.swing.JButton();
        lblTxt = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnavailable.setText("Available");
        btnavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavailableActionPerformed(evt);
            }
        });
        add(btnavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        tblMedicallist.setForeground(new java.awt.Color(36, 47, 65));
        tblMedicallist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Person", "Doctor", "Receiver", "Medicine List", "Status"
            }
        ));
        tblMedicallist.setFocusable(false);
        jScrollPane1.setViewportView(tblMedicallist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 630, 180));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ lablab.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 980, 840));

        btnNotavailable.setText("Not Available");
        btnNotavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotavailableActionPerformed(evt);
            }
        });
        add(btnNotavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        lblTxt.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblTxt.setText("Currently Logged in as:");
        add(lblTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 30));

        lblVal.setFont(new java.awt.Font("Optima", 1, 22)); // NOI18N
        lblVal.setText("<value>");
        add(lblVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavailableActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicallist.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        WorkRequest r = (WorkRequest) tblMedicallist.getModel().getValueAt(selectedRow, 0);
        r.setStatus("Available");
        populateTable();
        JOptionPane.showMessageDialog(this, "Made Available");
    }//GEN-LAST:event_btnavailableActionPerformed

    private void btnNotavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotavailableActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicallist.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a request");
            return;
        }
        WorkRequest r = (WorkRequest) tblMedicallist.getModel().getValueAt(selectedRow, 0);
        r.setStatus("Not available");
        populateTable();
        JOptionPane.showMessageDialog(this, "Not Available");
    }//GEN-LAST:event_btnNotavailableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotavailable;
    private javax.swing.JButton btnavailable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTxt;
    private javax.swing.JLabel lblVal;
    private javax.swing.JTable tblMedicallist;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblMedicallist.getModel();
        model.setRowCount(0);
        
            System.out.println("Outside for");
        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            System.out.println("inside for");
//            if(wr instanceof prescribeMedicine){
                
            System.out.println("wr found");
                row[0] = wr;
                row[1] = wr.getSender().getUsername();
                row[2] = wr.getReceiver().getUsername();
                String ml = ((prescribeMedicine) wr).getMedList();
                row[3] = ml;
                row[4] = wr.getStatus();
                model.addRow(row);
//            }
        }
    }
}
