/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Admin;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehadevarapalli
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;

    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;

        popOrganizationComboBox();
      
        popData();
    }

    public void popOrganizationComboBox() {
        cmbOrg.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            cmbOrg.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        cmbEmp.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            cmbEmp.addItem(employee);
        }
    }
    
    private void populateRoleComboBox(Organization organization){
        cmbRolebox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            cmbRolebox.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) tblUser.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        txtUsernamee = new javax.swing.JTextField();
        lblUsernamee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblEmp = new javax.swing.JLabel();
        cmbEmp = new javax.swing.JComboBox();
        lblOrg = new javax.swing.JLabel();
        cmbOrg = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        cmbRolebox = new javax.swing.JComboBox();
        separatorLine1 = new javax.swing.JSeparator();
        separatorLine2 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1190, 848));
        setPreferredSize(new java.awt.Dimension(1190, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        txtUsernamee.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtUsernamee.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernamee.setBorder(null);
        add(txtUsernamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 230, -1));

        lblUsernamee.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblUsernamee.setText("Username:");
        add(lblUsernamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        tblUser.setForeground(new java.awt.Color(0, 204, 204));
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUser.setGridColor(new java.awt.Color(97, 212, 195));
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(0).setResizable(false);
            tblUser.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 375, 179));

        lblPass.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPass.setText("Password:");
        add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        txtPass.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 230, -1));

        lblEmp.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEmp.setText("Employee:");
        add(lblEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        cmbEmp.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpActionPerformed(evt);
            }
        });
        add(cmbEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 300, -1));

        lblOrg.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblOrg.setText("Organization:");
        add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        cmbOrg.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });
        add(cmbOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 300, -1));

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 40, -1));

        cmbRolebox.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        cmbRolebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRolebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleboxActionPerformed(evt);
            }
        });
        add(cmbRolebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 300, -1));

        separatorLine1.setBackground(new java.awt.Color(0, 0, 0));
        separatorLine1.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine1.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine1.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 230, 10));

        separatorLine2.setBackground(new java.awt.Color(0, 0, 0));
        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine2.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine2.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 230, 10));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screen Shot 2022-12-08 at 12.17.27 AM.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 570, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
String userName = txtUsernamee.getText();
        String password = txtPass.getText();
        Organization organization = (Organization) cmbOrg.getSelectedItem();
        Employee employee = (Employee) cmbEmp.getSelectedItem();
        Role role = (Role) cmbRolebox.getSelectedItem();
        
        if(userName.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Please agree to the terms of service", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!Business.Validation.passwordValidator(password)){
            JOptionPane.showMessageDialog(null, "Password Criteria not Satisfied. Enter a password with 8 Characters, a Special character, 1 Uppercase and Numerical values", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        if(!organization.getUserAccountDirectory().checkIfUsernameIsUnique(userName)){
            JOptionPane.showMessageDialog(null, "Username already exists, select a new username", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        dB4OUtil.storeSystem(system);
        txtUsernamee.setText("");
        txtPass.setText("");
        popData();
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        Organization organization = (Organization) cmbOrg.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_cmbOrgActionPerformed

    private void cmbRoleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleboxActionPerformed

    private void cmbEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbEmp;
    private javax.swing.JComboBox cmbOrg;
    private javax.swing.JComboBox cmbRolebox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsernamee;
    private javax.swing.JSeparator separatorLine1;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsernamee;
    // End of variables declaration//GEN-END:variables
}
