package ui;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author nehadevarapalli
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signinPanel = new javax.swing.JPanel();
        signinFormPanel = new javax.swing.JPanel();
        lblSignin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        separatorLine2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        chkTerms = new javax.swing.JCheckBox();
        btnsignin = new javax.swing.JButton();
        separatorLine4 = new javax.swing.JSeparator();
        exiticon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinPanel.setBackground(new java.awt.Color(255, 255, 255));
        signinPanel.setPreferredSize(new java.awt.Dimension(1440, 900));
        signinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinFormPanel.setBackground(new java.awt.Color(0, 0, 51));
        signinFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignin.setFont(new java.awt.Font("Optima", 1, 23)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(255, 255, 255));
        lblSignin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignin.setText("Welcome To Vaccine Portal");
        signinFormPanel.add(lblSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 50));

        lblUsername.setFont(new java.awt.Font("Optima", 3, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("USERNAME");
        signinFormPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Optima", 3, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD");
        signinFormPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        signinFormPanel.add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 20));

        txtPassword.setBackground(new java.awt.Color(0, 0, 51));
        txtPassword.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("password");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        signinFormPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 300, 30));

        txtUsername.setBackground(new java.awt.Color(0, 0, 51));
        txtUsername.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setText("Enter Username");
        txtUsername.setBorder(null);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        signinFormPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 30));

        chkTerms.setBackground(new java.awt.Color(36, 47, 65));
        chkTerms.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        chkTerms.setForeground(new java.awt.Color(255, 255, 255));
        chkTerms.setText("I agree to all terms of service");
        signinFormPanel.add(chkTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        btnsignin.setBackground(new java.awt.Color(204, 204, 204));
        btnsignin.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        btnsignin.setText("Sign In");
        btnsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsigninMouseExited(evt);
            }
        });
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        signinFormPanel.add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 170, 40));

        separatorLine4.setForeground(new java.awt.Color(255, 255, 255));
        signinFormPanel.add(separatorLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 300, 10));

        signinPanel.add(signinFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 380, 350));

        exiticon.setBackground(new java.awt.Color(255, 255, 255));
        exiticon.setText("Exit");
        exiticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exiticonMousePressed(evt);
            }
        });
        signinPanel.add(exiticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1376, 14, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        signinPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 1520, 990));

        getContentPane().add(signinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btnsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseEntered
        // TODO add your handling code here:
        btnsignin.setForeground(Color.RED);

    }//GEN-LAST:event_btnsigninMouseEntered

    private void btnsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsigninMouseExited
        // TODO add your handling code here:
        btnsignin.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnsigninMouseExited

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsigninActionPerformed

    private void exiticonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exiticonMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exiticonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignin;
    private javax.swing.JCheckBox chkTerms;
    private javax.swing.JLabel exiticon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JSeparator separatorLine4;
    private javax.swing.JPanel signinFormPanel;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
