/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehadevarapalli
 */
public class ManageNetworkPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tblNetworkselect.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetworkselect = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        btnSub = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        separatorLine = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1190, 848));
        setPreferredSize(new java.awt.Dimension(1190, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNetworkselect.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        tblNetworkselect.setForeground(new java.awt.Color(36, 47, 65));
        tblNetworkselect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNetworkselect.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblNetworkselect);
        if (tblNetworkselect.getColumnModel().getColumnCount() > 0) {
            tblNetworkselect.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 440, 180));

        lblName.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        btnSub.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnSub.setText("Submit");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 390, -1, -1));

        txtName.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtName.setBorder(null);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 181, -1));

        separatorLine.setForeground(new java.awt.Color(0, 0, 0));
        separatorLine.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 180, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kisspng-healthcare-industry-health-care-business-digital-h-accessible-services-health-care-clipart-full-s-5d235f5891a896.4824455915625992565966.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -70, 830, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        
        String name = txtName.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Network Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Network network = system.createAndAddNetwork();
        network.setName(name);
        //stores in the database
        dB4OUtil.storeSystem(system);
        populateNetworkTable();
        txtName.setText("");
    }//GEN-LAST:event_btnSubActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSub;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JTable tblNetworkselect;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    
}
