

package ui.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author  nehadevarapalli
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        lblVal.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        lblVal = new javax.swing.JLabel();
        onePanel = new javax.swing.JPanel();
        lblOrg = new javax.swing.JLabel();
        organizationsicon = new javax.swing.JLabel();
        twoPanel = new javax.swing.JPanel();
        lblEmp = new javax.swing.JLabel();
        employeesicon = new javax.swing.JLabel();
        threePanel = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        usersicon = new javax.swing.JLabel();
        lblTxt = new javax.swing.JLabel();
        cardWorkPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(102, 204, 255));
        menuPanel.setForeground(new java.awt.Color(255, 255, 255));
        menuPanel.setMaximumSize(new java.awt.Dimension(250, 848));
        menuPanel.setMinimumSize(new java.awt.Dimension(250, 848));
        menuPanel.setPreferredSize(new java.awt.Dimension(250, 848));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVal.setFont(new java.awt.Font("Optima", 1, 22)); // NOI18N
        lblVal.setText("<value>");
        menuPanel.add(lblVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 230, 30));

        onePanel.setBackground(new java.awt.Color(102, 204, 255));
        onePanel.setForeground(new java.awt.Color(255, 255, 255));
        onePanel.setMaximumSize(new java.awt.Dimension(250, 40));
        onePanel.setMinimumSize(new java.awt.Dimension(250, 40));
        onePanel.setOpaque(false);
        onePanel.setPreferredSize(new java.awt.Dimension(250, 40));
        onePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onePanelMouseClicked(evt);
            }
        });
        onePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrg.setBackground(new java.awt.Color(102, 204, 255));
        lblOrg.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblOrg.setForeground(new java.awt.Color(255, 255, 255));
        lblOrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrg.setText("MANAGE ORGANIZATION");
        lblOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblOrg.setMaximumSize(new java.awt.Dimension(180, 20));
        lblOrg.setMinimumSize(new java.awt.Dimension(180, 20));
        lblOrg.setOpaque(true);
        lblOrg.setPreferredSize(new java.awt.Dimension(180, 20));
        onePanel.add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 207, -1));

        organizationsicon.setBackground(new java.awt.Color(102, 204, 255));
        organizationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageorganization.png"))); // NOI18N
        organizationsicon.setOpaque(true);
        onePanel.add(organizationsicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        menuPanel.add(onePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        twoPanel.setBackground(new java.awt.Color(102, 204, 255));
        twoPanel.setForeground(new java.awt.Color(255, 255, 255));
        twoPanel.setMaximumSize(new java.awt.Dimension(250, 40));
        twoPanel.setMinimumSize(new java.awt.Dimension(250, 40));
        twoPanel.setOpaque(false);
        twoPanel.setPreferredSize(new java.awt.Dimension(250, 40));
        twoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoPanelMouseClicked(evt);
            }
        });
        twoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmp.setBackground(new java.awt.Color(102, 204, 255));
        lblEmp.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmp.setText("MANAGE EMPLOYEES");
        lblEmp.setMaximumSize(new java.awt.Dimension(180, 20));
        lblEmp.setMinimumSize(new java.awt.Dimension(180, 20));
        lblEmp.setOpaque(true);
        lblEmp.setPreferredSize(new java.awt.Dimension(180, 20));
        twoPanel.add(lblEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, -1));

        employeesicon.setBackground(new java.awt.Color(102, 204, 255));
        employeesicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageemployees.png"))); // NOI18N
        employeesicon.setOpaque(true);
        twoPanel.add(employeesicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        menuPanel.add(twoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        threePanel.setBackground(new java.awt.Color(102, 204, 255));
        threePanel.setForeground(new java.awt.Color(255, 255, 255));
        threePanel.setMaximumSize(new java.awt.Dimension(250, 40));
        threePanel.setMinimumSize(new java.awt.Dimension(250, 40));
        threePanel.setOpaque(false);
        threePanel.setPreferredSize(new java.awt.Dimension(250, 40));
        threePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threePanelMouseClicked(evt);
            }
        });
        threePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setBackground(new java.awt.Color(102, 204, 255));
        lblUser.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("MANAGE USERS");
        lblUser.setMaximumSize(new java.awt.Dimension(180, 20));
        lblUser.setMinimumSize(new java.awt.Dimension(180, 20));
        lblUser.setOpaque(true);
        lblUser.setPreferredSize(new java.awt.Dimension(180, 20));
        threePanel.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, -1));

        usersicon.setBackground(new java.awt.Color(102, 204, 255));
        usersicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageuser.png"))); // NOI18N
        usersicon.setToolTipText("");
        usersicon.setOpaque(true);
        threePanel.add(usersicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuPanel.add(threePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        lblTxt.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblTxt.setText("Currently Logged in as:");
        menuPanel.add(lblTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 260, -1));

        cardWorkPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardWorkPanel.setForeground(new java.awt.Color(255, 255, 255));
        cardWorkPanel.setMinimumSize(new java.awt.Dimension(1190, 848));
        cardWorkPanel.setPreferredSize(new java.awt.Dimension(1190, 848));
        cardWorkPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor.jpeg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setPreferredSize(new java.awt.Dimension(640, 640));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cardWorkPanel.add(jLabel2, "card2");

        add(cardWorkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void threePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threePanelMouseClicked
        // TODO add your handling code here:
        setColor(threePanel);
        resetColor(new JPanel[]{onePanel,twoPanel});
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(cardWorkPanel, enterprise);
        cardWorkPanel.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) cardWorkPanel.getLayout();
        layout.next(cardWorkPanel);
    }//GEN-LAST:event_threePanelMouseClicked

    private void twoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoPanelMouseClicked
        // TODO add your handling code here:
        setColor(twoPanel);
        resetColor(new JPanel[]{onePanel,threePanel});
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(cardWorkPanel, enterprise.getOrganizationDirectory());
        cardWorkPanel.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) cardWorkPanel.getLayout();
        layout.next(cardWorkPanel);
    }//GEN-LAST:event_twoPanelMouseClicked

    private void onePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onePanelMouseClicked
        // TODO add your handling code here:
        setColor(onePanel);
        resetColor(new JPanel[]{twoPanel,threePanel});
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(cardWorkPanel, enterprise.getOrganizationDirectory(),account,enterprise);
        cardWorkPanel.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) cardWorkPanel.getLayout();
        layout.next(cardWorkPanel);
    }//GEN-LAST:event_onePanelMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardWorkPanel;
    private javax.swing.JLabel employeesicon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblTxt;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVal;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel onePanel;
    private javax.swing.JLabel organizationsicon;
    private javax.swing.JPanel threePanel;
    private javax.swing.JPanel twoPanel;
    private javax.swing.JLabel usersicon;
    // End of variables declaration//GEN-END:variables
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(23,35,51));
    }
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(36,47,65));
           
        }
    }
}
