/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ManufacturingRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ManufacturingOrganization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.Vaccine;
import Business.Organization.VaccineDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ruchachotalia
 */
public class AddVaccineJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private ManufacturingOrganization organization;
    private VaccineDirectory vaccineDirectory;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private UserAccount account;
    private Enterprise enterprise;
   
    /**
     * Creates new form AddVaccineJPanel
     */
    public AddVaccineJPanel(JPanel userProcessContainer, OrganizationDirectory directory, ManufacturingOrganization organization, VaccineDirectory vaccineDirectory, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.directory = directory;
        this.account = account;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.vaccineDirectory = vaccineDirectory;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddVacc = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSci = new javax.swing.JLabel();
        btnAddVacc = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtScientific = new javax.swing.JTextField();
        separatorLine = new javax.swing.JSeparator();
        separatorLine1 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        iconBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddVacc.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblAddVacc.setText("Add Vaccine");
        add(lblAddVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        lblName.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        lblSci.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblSci.setText("Scientific Name:");
        add(lblSci, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        btnAddVacc.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnAddVacc.setText("Add");
        btnAddVacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVaccActionPerformed(evt);
            }
        });
        add(btnAddVacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        txtName.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 250, -1));

        txtScientific.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtScientific.setBorder(null);
        add(txtScientific, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 250, -1));

        separatorLine.setForeground(new java.awt.Color(0, 0, 0));
        separatorLine.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 220, 10));

        separatorLine1.setForeground(new java.awt.Color(0, 0, 0));
        separatorLine1.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine1.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 220, 10));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kisspng-health-care-medicine-physician-hospital-book-doctor-appointment-online-clinic-management-s-5bedd4fdf17f04.4623187215423132139892.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 310, 1570, 600));

        iconBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        iconBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconBackMousePressed(evt);
            }
        });
        add(iconBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddVaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVaccActionPerformed
// TODO add your handling code here:
        if(txtName.getText().equals("") || txtScientific.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        if(validate(txtName.getText(), txtScientific.getText())){
            Vaccine newVaccine = new Vaccine();
            newVaccine.setName(txtName.getText());
            newVaccine.setScientificName(txtScientific.getText());
            newVaccine.setManufacturerName(organization.getName());
            newVaccine.setStatus("Pending");
            organization.addVaccine(newVaccine);
            System.out.println(organization.getName());
            JOptionPane.showMessageDialog(this, "Vaccine Added");
        }
        dB4OUtil.storeSystem(system);
        txtName.setText("");
        txtScientific.setText("");


                        
    }//GEN-LAST:event_btnAddVaccActionPerformed

    private void iconBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBackMousePressed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
            
        ManufacturingWorkAreaJPanel manufacturingWorkAreaJPanel = new ManufacturingWorkAreaJPanel(userProcessContainer, account, organization, enterprise, system);
        //component;
        userProcessContainer.add("ManufacturingWorkAreaJPanel", manufacturingWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        

    }//GEN-LAST:event_iconBackMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVacc;
    private javax.swing.JLabel iconBack;
    private javax.swing.JLabel lblAddVacc;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSci;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JSeparator separatorLine1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScientific;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String name, String sciName) {
        //To change body of generated methods, choose Tools | Templates.
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Name cannot be empty");
            return false;
        }
        if(sciName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Scientific Name cannot be empty");
            return false;
        }
        return true;
    }
}
