/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ManufacturingRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ManufacturingOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PurchaseInventory;
import Business.Organization.Vaccine;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.requestVaccine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruchachotalia
 */
public class OrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrdersJPanel
     */
    private EcoSystem system;
    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private ManufacturingOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public OrderJPanel(JPanel userProcessContainer, Enterprise enterprise, OrganizationDirectory directory, ManufacturingOrganization organization, UserAccount userAccount) {
        initComponents();
        this.directory = directory;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        lblComm = new javax.swing.JLabel();
        txtComm = new javax.swing.JTextField();
        btnApproved = new javax.swing.JButton();
        btnRejected = new javax.swing.JButton();
        separatorLine = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 375, 275));

        lblComm.setBackground(new java.awt.Color(0, 0, 0));
        lblComm.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblComm.setText("Comments:");
        add(lblComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        txtComm.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtComm.setBorder(null);
        add(txtComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 230, -1));

        btnApproved.setBackground(new java.awt.Color(0, 0, 0));
        btnApproved.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnApproved.setText("Approve");
        btnApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedActionPerformed(evt);
            }
        });
        add(btnApproved, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        btnRejected.setBackground(new java.awt.Color(0, 0, 0));
        btnRejected.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnRejected.setText("Reject");
        btnRejected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectedActionPerformed(evt);
            }
        });
        add(btnRejected, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        separatorLine.setBackground(new java.awt.Color(0, 0, 0));
        separatorLine.setForeground(new java.awt.Color(0, 0, 0));
        separatorLine.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 220, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doc.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
// TODO add your handling code here:
        for(Vaccine v : organization.getVaccineDirectory()){
            
            if(v.getStatus().equals("Approved")){
                
                int selectedRow = tblOrder.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select an order to approve");
            return;
        }
        requestVaccine request = (requestVaccine)tblOrder.getValueAt(selectedRow, 0);
        
        if(request.getStatus().equals("Approved")){
            JOptionPane.showMessageDialog(this, "Vaccine already approved");
            return;
        }
     
        if(validate(txtComm.getText())){
        request.setStatus("Approved");
        request.setTestResult("Approved");
        ArrayList<PurchaseInventory> inv = ((requestVaccine) request).getInventoryPurchase();
        if(inv!=null){
            for(PurchaseInventory p : inv){
                ((requestVaccine) request).setQty(p.getQty());
                
            }
            }


        
       
        
        populateTable();
        dB4OUtil.storeSystem(system);
        txtComm.setText("");
        }
        break;
            }
            else{
                JOptionPane.showMessageDialog(this, "You must have an approved vaccine in the inventory to manage orders");
                return;
            }
        }
    }//GEN-LAST:event_btnApprovedActionPerformed

    private void btnRejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectedActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select an order");
            return;
        }
        requestVaccine request = (requestVaccine)tblOrder.getValueAt(selectedRow, 0);
        
        if(request.getStatus().equals("Rejected") || request.getStatus().equals("Approved")){
            JOptionPane.showMessageDialog(this, "Vaccine already processed");
            return;
        }
     
        if(validate(txtComm.getText())){
        request.setStatus("Rejected");
        request.setTestResult("Rejected");

        populateTable();
        }
    }//GEN-LAST:event_btnRejectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproved;
    private javax.swing.JButton btnRejected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComm;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtComm;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.setRowCount(0);
        
        try{
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()){
            ArrayList<PurchaseInventory> inv = ((requestVaccine) wr).getInventoryPurchase();
            Object[] row = new Object[4];
            row[0] = wr;
            row[1] = wr.getReceiver().getUsername();
            if(inv!=null){
            for(PurchaseInventory p : inv){
                row[2] = p.getQty();
            }
            }
            row[3] = wr.getStatus();
            model.addRow(row);
        }
    }
        catch(NullPointerException e){
            
    }
    }

    private boolean validate(String comment) {
       if(comment.length()<1){
           JOptionPane.showMessageDialog(this, "Please enter comments");
           return false;
       }
           return true;
    }
    
}
